### ISSUE TITLE
Bring the CLI up-to-date

### ISSUE THREAD

**Issue by jp-andre** [microsoft/appcenter-cli#763]
The CLI has a lot of outdated dependencies, and does not even support node 12 properly. We need to work on some of those issues:
- [x] update all dependencies where it makes sense #767
- [x] remove typings from the code #771
- [ ] remove `request` #765
- [ ] remove gulp and use simple npm scripts instead #859
- [ ] remove `promisfied-fs.ts` which can be replaced by newer libs or the one-liner `utils.promisify()`
- [x] fix support for node 12
- [ ] update autorest ~and re-gen client api~ #769 
- [x] switch to eslint (see also #773)
- [ ] functional tests don't work with latest version of Pester

**Comment by jp-andre** [comment]
Work in progress:
- #767
- #765
